# Generated by Django 5.0.2 on 2024-03-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_lisence',
            field=models.ImageField(blank=True, null=True, upload_to='shop/license'),
        ),
    ]
