# Generated by Django 5.0.2 on 2024-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_shop', '0005_shop_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/shop-image'),
        ),
    ]
