# Generated by Django 5.0.2 on 2024-03-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_shop', '0006_shop_shop_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.CharField(blank=True, null=True),
        ),
    ]
