# Generated by Django 5.0.2 on 2024-04-01 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_shop', '0009_remove_shop_latitude_remove_shop_longitude_and_more'),
        ('products', '0008_delete_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products_used', models.ManyToManyField(to='products.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic_shop.service')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanic_shop.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
