# Generated by Django 5.0.2 on 2024-04-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_shop', '0010_servicebill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceBill',
        ),
    ]
