# Generated by Django 5.0.2 on 2024-04-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_shop', '0012_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='verification_status',
        ),
    ]
