# Generated by Django 5.0.2 on 2024-03-10 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('mechanic_shop', '0005_shop_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookservice',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_services', to='mechanic_shop.service'),
        ),
        migrations.AlterField(
            model_name='bookservice',
            name='vehicles',
            field=models.CharField(choices=[('two_wheelers', 'Two Wheelers'), ('four_wheelers', 'Four Wheelers'), ('both', 'Both')], max_length=100, null='True'),
        ),
    ]
