# Generated by Django 5.0.2 on 2024-04-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_invoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratebooking',
            name='review',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
