# Generated by Django 5.0.2 on 2024-04-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_ratebooking_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratebooking',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5),
        ),
        migrations.AlterField(
            model_name='ratebooking',
            name='review',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
