# Generated by Django 5.0.2 on 2024-03-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_bookservice_is_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookservice',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bookservice',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
