# Generated by Django 5.0.2 on 2024-04-16 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_user_groups_user_is_superuser_user_user_permissions'),
        ('bookings', '0004_ratebooking_rating_alter_ratebooking_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratebooking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.userprofile'),
        ),
    ]
