# Generated by Django 5.0.2 on 2024-04-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookservice_latitude_bookservice_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookservice',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
