# Generated by Django 5.0.2 on 2024-04-01 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_bookservice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookservice',
            name='time',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
