# Generated by Django 5.0.2 on 2024-04-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_bookservice_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookservice',
            old_name='time',
            new_name='date',
        ),
    ]
