# Generated by Django 5.0.2 on 2024-04-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_rename_time_bookservice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookservice',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
