# Generated by Django 5.0.2 on 2024-04-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_bookservice_shop'),
        ('products', '0008_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('service_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.bookservice')),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
    ]
