# Generated by Django 5.0.2 on 2024-04-01 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_bill'),
        ('products', '0008_delete_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bill',
            new_name='ServiceBill',
        ),
    ]
