# Generated by Django 5.0.2 on 2024-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_remove_invoice_product_and_more'),
        ('mechanic_shop', '0012_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookservice',
            name='services',
        ),
        migrations.AddField(
            model_name='bookservice',
            name='services',
            field=models.ManyToManyField(related_name='booked_services', to='mechanic_shop.service'),
        ),
    ]
