# Generated by Django 5.0.2 on 2024-04-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_remove_bookservice_services_bookservice_services'),
        ('mechanic_shop', '0012_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='service_hours',
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mechanic_shop.service'),
        ),
    ]
