# Generated by Django 5.0.2 on 2024-04-08 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_remove_invoice_service_hours_invoiceproduct_hours_and_more'),
        ('mechanic_shop', '0012_alter_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='service',
        ),
        migrations.CreateModel(
            name='InvoiceService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.invoice')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mechanic_shop.service')),
            ],
        ),
    ]
