# Generated by Django 5.0.2 on 2024-04-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='packing_cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax',
        ),
    ]
