# Generated by Django 5.0.2 on 2024-04-17 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic_shop', '0013_remove_shop_verification_status'),
        ('products', '0010_productpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpayment',
            name='product',
        ),
        migrations.AddField(
            model_name='productpayment',
            name='payment_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productpayment',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mechanic_shop.shop'),
        ),
        migrations.CreateModel(
            name='PurchasedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productpayment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='productpayment',
            name='products',
            field=models.ManyToManyField(through='products.PurchasedProduct', to='products.product'),
        ),
    ]
