# Generated by Django 5.0.2 on 2024-04-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productpayment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpayment',
            name='products',
        ),
        migrations.RemoveField(
            model_name='productpayment',
            name='shop',
        ),
        migrations.DeleteModel(
            name='PurchasedProduct',
        ),
    ]
